import { StyleSheet } from 'react-native';
export default StyleSheet.create({
    Principal:{padding: 20, flex:1},
    BoxInicial:{flex:2, marginTop:20},
    Box1:{flex:2, justifyContent:"center", flexDirection:"column", alignContent:"center",},
    Box2:{flex:1, justifyContent:"flex-end"},
    BoxCabecalho: {height: 35, justifyContent: "space-between", flexDirection:"row", padding:10, marginTop:10},
    BoxRodape: {height: 40, borderRadius: 30, backgroundColor: "#FFF", justifyContent: "flex-end",  flexDirection:"column", alignContent:"center", marginHorizontal:10},
    BoxRodapespace: {justifyContent: "space-between",  flexDirection:"row"},
    Boxmsg:{flex:2, flexDirection: "column", justifyContent:"center", alignItems:"center"},
    ButtonSelecionarClienteAtivo:{padding: 15, backgroundColor: "orange", height: 40, opacity: 1, borderRadius: 10, marginHorizontal:5},
    ButtonTextSelecionarcliente:{color: "#FFF", fontWeight: "bold", fontSize: 20},
    ButtonVoltar:{padding: 15, backgroundColor: "transparent", height: 20, marginHorizontal:5, opacity: 1},
    ButtonTextVoltar:{color: "#F63535", fontWeight: "bold", fontSize: 15},
    enderecosList: {marginVertical: 10, marginHorizontal: 10,},
    enderecos: {paddingHorizontal: 10,  borderRadius: 8,  backgroundColor: '#FFF', marginBottom: 16},
    enderecosselecionado: {padding: 10,  borderRadius: 8,  backgroundColor: '#BBFDC0', marginBottom: 16},
    enderecosProperty: {fontSize: 14, color: '#41414d', fontWeight: 'bold'} ,
    enderecosValue: {marginTop: 5, fontSize: 15, marginBottom: 5, color: '#737380'}, 
    textmsg:{fontSize:20, fontWeight: "bold", }, 
    ButtonTextSucesso: {color: "green", fontWeight:"bold"},
    ButtonTextErro: {color: "red", fontWeight:"bold"},
    textcabecalho: {fontWeight: "bold"}, 
    ButtonTransparentAtivo: {padding: 20, backgroundColor: "transparent", height: 20, marginHorizontal:5, },
    ButtonTransparentInativo: {padding: 20, backgroundColor: "transparent", height: 20, marginHorizontal:5, opacity: 0.25},
    ButtonTextSucessolink: {color: "green", fontWeight:"bold", fontSize: 15},
    ButtonFinalizarInativo: {padding: 15, backgroundColor: "#3CB371", height: 40, opacity: 0.25, borderRadius: 7, marginHorizontal:5},
    ButtonFinalizarAtivo: {padding: 15, backgroundColor: "#3CB371", height: 40, opacity: 1, borderRadius: 7, marginHorizontal:5},
    container: {flex: 1, justifyContent: 'flex-end', alignItems: 'flex-end',},
    map: {position: 'absolute',top: 0,left: 0,right: 0,bottom: 0,},
    buttonmedioleft: {width: '85%',height: 40,backgroundColor: 'transparent',alignItems: 'center',justifyContent: 'center',borderWidth: 1, borderColor: 'red',borderRadius: 7, marginBottom: 15,},
    buttonmedioleftText: {color: 'red', fontWeight: 'bold',},
    buttonmedioright: {width: '85%',height: 40,backgroundColor: 'transparent',alignItems: 'center',justifyContent: 'center',borderWidth: 1,borderColor: 'orange',borderRadius: 7, marginBottom: 15, marginRight: '15%',},
    buttonmediorightText: {color: 'orange', fontWeight: 'bold',},
    inputContainer: {width: '90%', maxHeight: 200, alignItems: 'center',justifyContent: 'space-between', flexDirection: 'row'},
    buttonTextiniciarota: {color: 'green', fontWeight: 'bold',},
    buttoniniciarota: {width: '85%',height: 40,backgroundColor: 'transparent',alignItems: 'center',justifyContent: 'center',borderWidth: 1,borderColor: 'green',borderRadius: 7, marginBottom: 15,},
    ButtonRemoveCliente: {padding: 5, backgroundColor: "red", height: 20, borderRadius: 7},
    ButtonRemoveClienteText: {color: "#000", fontWeight: "bold", fontSize: 20},
    ButtonLeitor: {padding: 5, backgroundColor: "#363636", height: 35},
    ButtonLeitorText: {color: "#FFF", fontWeight: "bold", fontSize: 16},
    containerScanner: {flex: 1, flexDirection: 'column', justifyContent: 'flex-end'},
    spinnerTextStyle: { color: '#FFF'},
    containerspinner: {flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#F5FCFF'},
    ContainerStyle:{ padding: 5, width: '100%'},
    TextInputStyle:{paddingHorizontal: 20 , borderWidth: 1, borderColor: '#ccc', borderRadius: 5, height: 40, fontSize: 20},
    ItemStyle: { padding: 10, marginTop: 2, backgroundColor: '#363636', borderColor: '#FFF', borderWidth: 1, borderRadius: 5, },
    ItemTextStyle: {color: '#FFF'},
    ItemsContainerStyle: { maxHeight: 140},

});