import { StyleSheet } from 'react-native';
export default StyleSheet.create({
    Principal:{padding: 20,  flex:1 },
    BoxInicial:{flex:2, marginTop:20},
    ContainerStyle:{ padding: 5, width: '100%'},
    BoxRodape: {height: 40, borderRadius: 30, backgroundColor: "#FFF", justifyContent: "flex-end",  flexDirection:"column", alignContent:"center", marginHorizontal:20},
    TextInputStyle:{paddingHorizontal: 20 , borderWidth: 1, borderColor: '#ccc', borderRadius: 5, height: 40, fontSize: 20},
    TextInputModal:{marginBottom: 10, borderWidth: 0, height: 23, fontSize: 20},
    IconModal:{marginBottom: 10},
    ItemStyle: { padding: 10, marginTop: 2, backgroundColor: '#363636', borderColor: '#FFF', borderWidth: 1, borderRadius: 5, },
    ItemTextStyle: {color: '#FFF'},
    ItemsContainerStyle: { maxHeight: 140},
    TableborderStyle:{borderColor: 'transparent'},
	head: { height: 40, backgroundColor: '#363636' },
    headtext: { margin: 6, color: '#fff', fontWeight: "bold", fontSize: 17 },
    row: { flexDirection: 'row', backgroundColor: '#ccc' },
    rowtext: { margin: 6, color: '#4F4F4F', fontWeight: "bold",  fontSize: 17 },
    btnrow: { width: 32, height: 32, padding: 5, backgroundColor: '#363636',  borderRadius: 5, margin: 10, alignItems: "center" },
    btnText: { textAlign: 'center', color: '#fff' },
    ContainerTable: {padding: 16, backgroundColor: "#fff", marginBottom: 100},
    InputObjeto:{ width: 220, height: 40},
    ButtonObjetoAtivo: {padding: 20, backgroundColor: "#363636", height: 40, opacity: 1, fontSize: 22},
    ButtonObjetoInativo: {padding: 20, backgroundColor: "#363636", height: 40, opacity: 0.25, fontSize: 22},
    ButtonLeitor: {padding: 5, backgroundColor: "#363636", height: 35},
    ButtonLeitorText: {color: "#FFF", fontWeight: "bold", fontSize: 16},
    ButtonFinalizarAtivo: {padding: 15, backgroundColor: "#3CB371", height: 40, opacity: 1},
    ButtonFinalizarInativo: {padding: 15, backgroundColor: "#3CB371", height: 40, opacity: 0.25},
    ButtonCancelar: {padding: 15, backgroundColor: "#FF6347", height: 40},
    ButtonText: {color: "#FFF", fontWeight: "bold", fontSize: 20},
    container: {flex: 1, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', },
    containerScanner: {flex: 1, flexDirection: 'column', justifyContent: 'flex-end'},
    spinnerTextStyle: { color: '#FFF'},
    containerspinner: {flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#F5FCFF'},
    ButtonTextErro: {color: "#F63535", fontWeight: "bold", fontSize: 20},
    ButtonTransparentAtivo: {padding: 15, backgroundColor: "transparent", height: 40, marginHorizontal:5, opacity: 1},
    ButtonTextVoltar:{color: "#F63535", fontWeight: "bold", fontSize: 15},
    ButtonVoltar:{padding: 15, backgroundColor: "transparent", height: 20, marginHorizontal:5, opacity: 1},
    
    
});